### ISSUE TITLE
less-579 will not compile under Windows

### ISSUE THREAD

**Issue by jftuga** [gwsw/less#126]
To compile , I am using:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
nmake /f Makefile.wnm
```

* `less-576` will compile
* `less-577` will not

Here is the `less-576` compilation error message:

```
lsystem.obj : error LNK2019: unresolved external symbol tty_device referenced in function lsystem
less.exe : fatal error LNK1120: 1 unresolved externals
```

Here is the difference in `lsystem.c`:
```
diff less-576\lsystem.c less-577\lsystem.c

121c121
<       if (__open("/dev/tty", OPEN_READ) < 0)
---
>       if (__open(tty_device(), OPEN_READ) < 0)
123c123
<       if (open("/dev/tty", OPEN_READ) < 0)
---
>       if (open(tty_device(), OPEN_READ) < 0)
```

In the `less-579` code, I reverted these back to using `"/dev/tty"` and the compilation was then successful.  However, I doubt this is the best fix for this problem and therefore did not submit a PR.  I suspect that the `tty_device()` function needs to be changed, but I did not have time to further investigate.

**Comment by gwsw** [comment]
I'm not sure what you mean by "v579" -- that tag has not yet been built. In any case, this bug should be fixed in 0c08883a66a5ad4039f9587401872d9e390b09e3.

**Comment by jftuga** [comment]
I was testing with this:

http://greenwoodsoftware.com/less/less-579.tar.gz

This tarball actually includes the `0c08883` patch, but still fails to compile.

**Comment by gwsw** [comment]
Ah, sorry, I'm still in the process of preparing v579 and forgot that that had been uploaded.

Well, that's strange that you're getting that error with that code, since the call to tty_device is surrounded by
```
#if !MSDOS_COMPILER
```
MSDOS_COMPILER should be WIN32C (3) if you build with Makefile.wnm.

**Comment by jftuga** [comment]
Is there anyway I can tell if that is actually set or not?

**Comment by gwsw** [comment]
You could try something like this:
```
   inp = dup(0);
    close(0);
+#define _XSTR(x) _STR(x)
+#define _STR(x) #x
+#warning "MSDOS_COMPILER is " _XSTR(MSDOS_COMPILER)
+#pragma message "MSDOS_COMPILER is " _XSTR(MSDOS_COMPILER)
 #if !MSDOS_COMPILER
 #if OS2
    /* The __open() system call translates "/dev/tty" to "con". */
```

**Comment by jftuga** [comment]
That did not work but I *think* I found [something similar](https://stackoverflow.com/a/2465451):

```
#define STRINGIFY( L )       #L
#define MAKESTRING( M, L )   M(L)
#define STRINGIZE(X)         MAKESTRING( STRINGIFY, X )
#pragma message( "You have " STRINGIZE(MSDOS_COMPILER) )
```

When compiling, this is what is returned:

`You have 3`

Please let me know if my replacement is not what you are looking for.

**Comment by gwsw** [comment]
So you have MSDOS_COMPILER == 3, but the code inside ``#if !MSDOS_COMPILER`` is being compiled? That's difficult to understand.

**Comment by jftuga** [comment]
I agree.  I am not sure what to make of it.  Do the `define` and ` pragma` statements that I previously posted look OK to you?

**Comment by gwsw** [comment]
Yes they look ok, and 3 (WIN32C) is the value I would expect MSDOS_COMPILER to be set to (defined in defines.wn). I don't understand why code under #if !MSDOS_COMPILER would be compiled. That construct is used elsewhere, for example in screen.c, where it must be working.

**Comment by jftuga** [comment]
Could you add something like

    #if MSDOS_COMPILER == 3

I don't know / remember a lot about `C preprocessor` statements.

**Comment by gwsw** [comment]
Please check whether https://greenwoodsoftware.com/less/less-580.tar.gz works for you.

**Comment by jftuga** [comment]
> Please check whether https://greenwoodsoftware.com/less/less-580.tar.gz works for you.

Version `580` compiles:

    03/03/2021  04:21 PM           327,168 less.exe
    03/03/2021  04:21 PM           143,872 lesskey.exe

Version check:

    .\less.exe --version
    less 580 (Spencer V8 regular expressions)

Thank you for working on this with me. I really appreciate it.
